autogrem/autogrem/urls.py
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView
from django.urls import path, include

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('favicon.ico', RedirectView.as_view(url='/static/favicon.ico')),
    path("finance/", include("finance.urls")),
    path('admin/', admin.site.urls),
]

autogrem/finance/urls.py
from django.urls import path

from . import views

app_name = "finance"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("bill/new/", views.new_bill, name="new-bill"),
    path("<int:pk>/", views.RecurringBillDetailsView.as_view(), name="bill-detail"),
]

autogrem/finance/models.py
import abc
from datetime import date
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

class AbstractModelMeta(abc.ABCMeta, type(models.Model)):
    """
    Python sourcery so we can make abstract Model classes

    Usage:
        class AbstractModelClass(models.Model, metaclass=AbstractModelMeta):
    """
    pass

class Transaction(models.Model, metaclass=AbstractModelMeta):
    """
    Abstract class representing a financial transaction.
    """
    name = models.CharField(max_length=30)
    # allows amounts up to 999,999.99
    amount = models.DecimalField(max_digits=8, decimal_places=2)

    @abc.abstractmethod
    def is_recent(self) -> bool:
        pass

    class Meta:
        abstract = True

class Purchase(Transaction):
    """
    A one-time purchase.
    """
    transaction_date = models.DateField(default=date.today)

    def is_recent(self) -> bool:
        return True

    def __str__(self) -> str:
        return f"Transaction on {self.transaction_date} of ${self.amount}"

class TimeUnit(models.TextChoices):
    """
    Represents a unit of time. Can be used as an option for selection fields.
    """
    YEAR = "Y", _("Year")
    MONTH = "M", _("Month")
    DAY = "D", _("Day")
    HOUR = "h", _("Hour")
    MINUTE = "m", _("Minute")
    SECOND = "s", _("Second")
    DAY_OF_WEEK = "DOW", _("Day of the week")
    DAY_OF_YEAR = "DOY", _("Day of the year")

class Bill(Transaction):
    """
    A recurring purchase with flexible duration options.
    """
    
    start_date = models.DateField(verbose_name="start date", default=date.today)
    is_indefinate = models.BooleanField(default=True)

    # In the Django admin any field with blank=False is marked as a required.
    # If you don't set a value for these fields your form will have a validation 
    # error even if the field is nullable!
    # 
    # ;tldr is to use both blank=True and null=True
    end_date = models.DateField(verbose_name="end date", blank=True, null=True)
    
    duration = models.IntegerField()
    duration_unit = models.CharField(max_length=3,
                                 choices=TimeUnit,
                                 default=TimeUnit.DAY)
    
    def is_recent(self) -> bool:
        return False

autogrem/finance/forms.py
from django import forms
from .models import Bill

class NewBill(forms.ModelForm):
    
    class Meta:
        model = Bill
        fields = ['name', 'amount', 'start_date', 'is_indefinate', 'end_date',
                  'duration', 'duration_unit', ]

autogrem/finance/views.py
from typing import Any
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views.generic import DetailView, ListView

from .forms import NewBill
from .models import Bill

class IndexView(ListView):    
    """Extend the generic ListView view to take advantage of django's
    abstraction of the concept of “display a list of objects.”

    This means we can skip the overhead of writing a million methods like
    this:
    
    def index(request):
    try:
        objects = MyObject.objects.all()
    except Exception:
        raise Http404("MyObject does not exist")
    return render(request, "myapp/index.html", {"objects": objects})
    """
    
    # let django know what to render
    template_name = "finance/index.html"
    
    # the ListView superclass will call get_queryset() automatically
    # this variable is what we will name the variable we pass to our template
    # see autogrem/finance/templates/finance/index.html to see how we use it
    context_object_name = "expenses"
    
    paginate_by=10

    def get_queryset(self) -> QuerySet[Any]:
        return Bill.objects.all().order_by("name")

class RecurringBillDetailsView(DetailView):
    model = Bill
    template_name = "finance/bill_detail.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context

def new_bill(request):
    user = User.objects.first() # TODO: get the logged in user!
    
    if request.method == 'POST':
        form = NewBill(request.POST)
        if form.is_valid():
            bill = form.save()
            # go back to the finance home page
            return HttpResponseRedirect(reverse('finance:index'))
    else:
        form = NewBill()
    return render(request, 'finance/new_bill.html', {'form': form})

autogrem/finance/templates/finance/base.html
{% load static %}<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- tab title -->
    <title>Autogrem</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'finance:index' %}">Autogrem</a>
        </div>
    </nav>
    <div class="container mb-3">
        <ol class="breadcrumb my-4">
            {% block breadcrumb %}
            {% endblock %}
        </ol>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

autogrem/finance/templates/finance/bill_detail.html
<h1>{{ object.name }}</h1>
<p>{{ object.content }}</p>
<!-- <p>Reporter: {{ object.reporter }}</p>
<p>Published: {{ object.pub_date|date }}</p> -->
<p>Date: {{ now|date }}</p>

autogrem/finance/templates/finance/index.html
{% extends "base.html" %}

{% block breadcrumb %}
<li class="breadcrumb-item-active">Finance</li>
{% endblock breadcrumb %}

{% block content %}
<table class="table table-hover">
    <thead class="thead-inverse">
        <tr class="text-center">
            <th class="text-start">Expense</th>
            <th>Amount</th>
            <th>Last Payment</th>
            <th>Next Payment on</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for expense in expenses %}
        <tr class="text-center">
            <td class="text-start">
                <a href="{{ expense.id }}">{{ expense.name }}</a>
            </td>
            <td>
                ${{ expense.amount }}
            </td>
            <td>0</td>
            <td>0</td>
            <td>
                <button type="button" class="btn btn-outline-primary">Modify</button>
                <button type="button" class="btn btn-outline-danger">Delete</button>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

autogrem/finance/templates/finance/new_bill.html
{% extends "base.html" %}

{% comment %} Load django-widget-tweaks app {% endcomment %}
{% load widget_tweaks %}

{% block title %}Create a New Bill{% endblock %}

{% block content %}
<form method="post" novalidate>
    {% csrf_token %}
    
    {% for field in form.visible_fields %}
    <div class="form-group">
        <div class="row align-items-center mb-3">
            <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">{{ field.label }}</label>
            <div class="col align-items-start">
                {% with WIDGET_ERROR_CLASS='is-invalid'%}
                {% if field|widget_type == 'checkboxinput' %}
                {% render_field field class="form-check-input" %}
                {% else %}
                {% render_field field class="form-control" %}
                {% endif %}
                {% comment %} this only executed if form validation fails {% endcomment %}
                {% if field.errors %}
                {% for error in field.errors %}
                <div class="invalid-feedback">
                    {{ error }}
                </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>
    </div>
    {% endfor %}
    
    <button type="submit" class="btn btn-success">Create</button>
</form>
{% endblock  %}

autogrem/finance/templates/finance/recurring_bill_detail.html
<h1>{{ object.name }}</h1>
<p>{{ object.content }}</p>
<!-- <p>Reporter: {{ object.reporter }}</p>
<p>Published: {{ object.pub_date|date }}</p> -->
<p>Date: {{ now|date }}</p>

autogrem/templates/base.html
{% load static %}<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <!-- tab title -->
    <title>Autogrem</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'home' %}">Autogrem</a>
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'finance:index' %}">Finances</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'finance:new-bill' %}">Expense</a>
                </li>
            </div>
        </nav>
        <div class="container mb-3">
            <ol class="breadcrumb my-4">
                {% block breadcrumb %}
                {% endblock %}
            </ol>
            {% block content %}
            {% endblock %}
        </div>
    </body>
    </html>

autogrem/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>WELCOME</h1>
{% endblock content %}